# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import firestore_pb2 as firestore__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in firestore_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class firestoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/firestore.firestore/Register',
                request_serializer=firestore__pb2.UserRegister.SerializeToString,
                response_deserializer=firestore__pb2.RegisterResult.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/firestore.firestore/Login',
                request_serializer=firestore__pb2.UserLogin.SerializeToString,
                response_deserializer=firestore__pb2.LoginResult.FromString,
                _registered_method=True)
        self.PatientInfo = channel.unary_unary(
                '/firestore.firestore/PatientInfo',
                request_serializer=firestore__pb2.UserID.SerializeToString,
                response_deserializer=firestore__pb2.PatientData.FromString,
                _registered_method=True)
        self.GetRisk = channel.unary_unary(
                '/firestore.firestore/GetRisk',
                request_serializer=firestore__pb2.UserID.SerializeToString,
                response_deserializer=firestore__pb2.RiskResponse.FromString,
                _registered_method=True)
        self.DoctorInfo = channel.unary_unary(
                '/firestore.firestore/DoctorInfo',
                request_serializer=firestore__pb2.UserID.SerializeToString,
                response_deserializer=firestore__pb2.DoctorData.FromString,
                _registered_method=True)
        self.GetPatients = channel.unary_unary(
                '/firestore.firestore/GetPatients',
                request_serializer=firestore__pb2.UserID.SerializeToString,
                response_deserializer=firestore__pb2.PatientsResponse.FromString,
                _registered_method=True)
        self.GetTestHistory = channel.unary_unary(
                '/firestore.firestore/GetTestHistory',
                request_serializer=firestore__pb2.UserID.SerializeToString,
                response_deserializer=firestore__pb2.TestHistoryResponse.FromString,
                _registered_method=True)
        self.SendLifestyle = channel.unary_unary(
                '/firestore.firestore/SendLifestyle',
                request_serializer=firestore__pb2.LifestyleRequest.SerializeToString,
                response_deserializer=firestore__pb2.LifestyleResponse.FromString,
                _registered_method=True)
        self.SendTranscript = channel.unary_unary(
                '/firestore.firestore/SendTranscript',
                request_serializer=firestore__pb2.LifestyleRequest.SerializeToString,
                response_deserializer=firestore__pb2.LifestyleResponse.FromString,
                _registered_method=True)
        self.SendMinimental = channel.unary_unary(
                '/firestore.firestore/SendMinimental',
                request_serializer=firestore__pb2.LifestyleRequest.SerializeToString,
                response_deserializer=firestore__pb2.LifestyleResponse.FromString,
                _registered_method=True)
        self.SendPatientDementia = channel.unary_unary(
                '/firestore.firestore/SendPatientDementia',
                request_serializer=firestore__pb2.DementiaRequest.SerializeToString,
                response_deserializer=firestore__pb2.DementiaResponse.FromString,
                _registered_method=True)
        self.GetNews = channel.unary_unary(
                '/firestore.firestore/GetNews',
                request_serializer=firestore__pb2.NewsRequest.SerializeToString,
                response_deserializer=firestore__pb2.NewsResponse.FromString,
                _registered_method=True)


class firestoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PatientInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRisk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DoctorInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPatients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTestHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendLifestyle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTranscript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMinimental(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPatientDementia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_firestoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=firestore__pb2.UserRegister.FromString,
                    response_serializer=firestore__pb2.RegisterResult.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=firestore__pb2.UserLogin.FromString,
                    response_serializer=firestore__pb2.LoginResult.SerializeToString,
            ),
            'PatientInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.PatientInfo,
                    request_deserializer=firestore__pb2.UserID.FromString,
                    response_serializer=firestore__pb2.PatientData.SerializeToString,
            ),
            'GetRisk': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRisk,
                    request_deserializer=firestore__pb2.UserID.FromString,
                    response_serializer=firestore__pb2.RiskResponse.SerializeToString,
            ),
            'DoctorInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.DoctorInfo,
                    request_deserializer=firestore__pb2.UserID.FromString,
                    response_serializer=firestore__pb2.DoctorData.SerializeToString,
            ),
            'GetPatients': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatients,
                    request_deserializer=firestore__pb2.UserID.FromString,
                    response_serializer=firestore__pb2.PatientsResponse.SerializeToString,
            ),
            'GetTestHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTestHistory,
                    request_deserializer=firestore__pb2.UserID.FromString,
                    response_serializer=firestore__pb2.TestHistoryResponse.SerializeToString,
            ),
            'SendLifestyle': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLifestyle,
                    request_deserializer=firestore__pb2.LifestyleRequest.FromString,
                    response_serializer=firestore__pb2.LifestyleResponse.SerializeToString,
            ),
            'SendTranscript': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTranscript,
                    request_deserializer=firestore__pb2.LifestyleRequest.FromString,
                    response_serializer=firestore__pb2.LifestyleResponse.SerializeToString,
            ),
            'SendMinimental': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMinimental,
                    request_deserializer=firestore__pb2.LifestyleRequest.FromString,
                    response_serializer=firestore__pb2.LifestyleResponse.SerializeToString,
            ),
            'SendPatientDementia': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPatientDementia,
                    request_deserializer=firestore__pb2.DementiaRequest.FromString,
                    response_serializer=firestore__pb2.DementiaResponse.SerializeToString,
            ),
            'GetNews': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNews,
                    request_deserializer=firestore__pb2.NewsRequest.FromString,
                    response_serializer=firestore__pb2.NewsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'firestore.firestore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('firestore.firestore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class firestore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/firestore.firestore/Register',
            firestore__pb2.UserRegister.SerializeToString,
            firestore__pb2.RegisterResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/firestore.firestore/Login',
            firestore__pb2.UserLogin.SerializeToString,
            firestore__pb2.LoginResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PatientInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/firestore.firestore/PatientInfo',
            firestore__pb2.UserID.SerializeToString,
            firestore__pb2.PatientData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRisk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/firestore.firestore/GetRisk',
            firestore__pb2.UserID.SerializeToString,
            firestore__pb2.RiskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DoctorInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/firestore.firestore/DoctorInfo',
            firestore__pb2.UserID.SerializeToString,
            firestore__pb2.DoctorData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPatients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/firestore.firestore/GetPatients',
            firestore__pb2.UserID.SerializeToString,
            firestore__pb2.PatientsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTestHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/firestore.firestore/GetTestHistory',
            firestore__pb2.UserID.SerializeToString,
            firestore__pb2.TestHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendLifestyle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/firestore.firestore/SendLifestyle',
            firestore__pb2.LifestyleRequest.SerializeToString,
            firestore__pb2.LifestyleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTranscript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/firestore.firestore/SendTranscript',
            firestore__pb2.LifestyleRequest.SerializeToString,
            firestore__pb2.LifestyleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMinimental(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/firestore.firestore/SendMinimental',
            firestore__pb2.LifestyleRequest.SerializeToString,
            firestore__pb2.LifestyleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPatientDementia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/firestore.firestore/SendPatientDementia',
            firestore__pb2.DementiaRequest.SerializeToString,
            firestore__pb2.DementiaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/firestore.firestore/GetNews',
            firestore__pb2.NewsRequest.SerializeToString,
            firestore__pb2.NewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
