#!/usr/bin/bash

# passis123456@example.com, password:123456
[ $1 == "test" ] && { curl -X POST -d '{"name":"Bob"}' http://localhost:80/v1/say_hello; exit; }
[ $1 == "keras" ] && { curl -X POST -d '{"UserID":"__testing__","DateTime":"2025-12-10","data":"Diabetic:true,AlcoholLevel:0.084973629, HeartRate:98, BloodOxygenLevel:96.23074296, BodyTemperature:36.22485168, Weight:57.56397754, MRI_Delay:36.42102798, Presecription:None, DosageMg:0, Age:60, EducationLevel:Primary School, DominantHand:Left, Gender:Female, FamilyHistory:false, SmokingStatus:Current Smoker, APOE_e19:false, PhysicalActivity:Sedentary, DepressionStatus:false, MedicationHistory:false, NutritionDiet:Low-Carb Diet, SleepQuality:Poor, ChronicHealthConditionsDiabetes"}' http://localhost:80/v1/send_lifestyle; exit; }
[ $1 == "kerasOnline" ] && { curl -X POST -d '{"UserID":"__testing__","dateTime":"2025-12-10","data":"Diabetic:true,AlcoholLevel:0.084973629, HeartRate:98, BloodOxygenLevel:96.23074296, BodyTemperature:36.22485168, Weight:57.56397754, MRI_Delay:36.42102798, Presecription:None, DosageMg:0, Age:60, EducationLevel:Primary School, DominantHand:Left, Gender:Female, FamilyHistory:false, SmokingStatus:Current Smoker, APOE_e19:false, PhysicalActivity:Sedentary, DepressionStatus:false, MedicationHistory:false, NutritionDiet:Low-Carb Diet, SleepQuality:Poor, ChronicHealthConditionsDiabetes"}' http://dementica.danigoes.online:80/v1/send_lifestyle; exit; }
[ $1 == "newsD" ] && { curl -X POST -d '{"Type":"Doctor"}' http://localhost:80/v1/get_news; exit; }
[ $1 == "newsP" ] && { curl -X POST -d '{"Type":"Doctor"}' http://localhost:80/v1/get_news; exit; }
[ $1 == "signup" ] && { curl -X POST -d '{"Name":"test","Password":"123456","RegisterWith":"test@example.com","RegType":"Email","UserType":"Patient"}' http://localhost:80/v1/register; exit; }
[ $1 == "login" ] && { curl -X POST -d '{"Email":"test@example.com","Password":"123456","UserType":"Patient"}' http://localhost:80/v1/login; exit; }
[ $1 == "patientInfo" ] && { curl -X POST -d "{'UserID': '$2' }" http://localhost:80/v1/patient_info; exit; }
[ $1 == "transcript" ] && { curl -X POST -d '{"UserID":"__testing__","data":"It has a nice pool and the children are trying to get the cookies.","dateTime":"2025-12-10"}' http://localhost:80/v1/send_transcript; exit; }
[ $1 == "transcript2" ] && { curl -X POST -d '{"UserID":"__testing__","data":"well uh for one thing this boys on the stool getting cookies.  and his stools about to fall.  and and the little girls reaching for some cookies.  she got her finger in her mouth.  um the mothers drying dishes and waters running over.  she got her, pl yeah and she drying dishes waters running over.  shes standing in water.  theres a sink there.  plate and a cup.  outside you can see outside there the the walkway and hedges, a window, tree.  and uh outside the, cup the cookie jar would hafta be in the cupboard.  and theres a what you call it, the counter on in the kitchen.  thats, and the curtains.  and the window.","dateTime":"2025-12-10"}' http://localhost:80/v1/send_transcript; exit; }
[ $1 == "mental" ] && { curl -X POST -d '{"UserID":"__testing__","data":"5","DateTime":"2025-02-12"}' http://localhost:80/v1/send_minimental; exit; }
[ $1 == "newsSet" ] && { curl -X POST -d '{"Type":"Patient","Content":"test"}' http://localhost:80/v1/set_news; exit; }

[ $1 == "build" ] && { sudo docker-compose -f docker-compose.yaml build && sudo docker-compose -f docker-compose.yaml up; }
[ $1 == "run" ] && { sudo docker-compose -f docker-compose.yaml up; }
