#!/usr/bin/bash


[ $1 == "test" ] && { curl -X POST -d '{"name":"Bob"}' http://localhost:80/v1/say_hello; exit; }

[ $1 ] && sudo docker-compose -f docker-compose.yaml build


sudo docker-compose -f docker-compose.yaml up
