# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vertex.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vertex.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvertex.proto\x12\taiProompt\"\x1d\n\nProomptMsg\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\rProomptReturn\x12\x0f\n\x07message\x18\x01 \x01(\t2P\n\taiProompt\x12\x43\n\x10HealtcareProompt\x12\x15.aiProompt.ProomptMsg\x1a\x18.aiProompt.ProomptReturnB\x13Z\x11\x65xample/aiProomptb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vertex_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\021example/aiProompt'
  _globals['_PROOMPTMSG']._serialized_start=27
  _globals['_PROOMPTMSG']._serialized_end=56
  _globals['_PROOMPTRETURN']._serialized_start=58
  _globals['_PROOMPTRETURN']._serialized_end=90
  _globals['_AIPROOMPT']._serialized_start=92
  _globals['_AIPROOMPT']._serialized_end=172
# @@protoc_insertion_point(module_scope)
