// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: firestore.proto

package proto_example

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Firestore_Register_FullMethodName            = "/firestore.firestore/Register"
	Firestore_Login_FullMethodName               = "/firestore.firestore/Login"
	Firestore_PatientInfo_FullMethodName         = "/firestore.firestore/PatientInfo"
	Firestore_GetRisk_FullMethodName             = "/firestore.firestore/GetRisk"
	Firestore_DoctorInfo_FullMethodName          = "/firestore.firestore/DoctorInfo"
	Firestore_GetPatients_FullMethodName         = "/firestore.firestore/GetPatients"
	Firestore_GetTestHistory_FullMethodName      = "/firestore.firestore/GetTestHistory"
	Firestore_SendLifestyle_FullMethodName       = "/firestore.firestore/SendLifestyle"
	Firestore_SendPatientDementia_FullMethodName = "/firestore.firestore/SendPatientDementia"
	Firestore_GetNews_FullMethodName             = "/firestore.firestore/GetNews"
)

// FirestoreClient is the client API for Firestore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FirestoreClient interface {
	Register(ctx context.Context, in *UserRegister, opts ...grpc.CallOption) (*RegisterResult, error)
	Login(ctx context.Context, in *UserLogin, opts ...grpc.CallOption) (*LoginResult, error)
	PatientInfo(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*PatientData, error)
	GetRisk(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*RiskResponse, error)
	DoctorInfo(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*DoctorData, error)
	GetPatients(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*PatientsResponse, error)
	GetTestHistory(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*TestHistoryResponse, error)
	SendLifestyle(ctx context.Context, in *LifestyleRequest, opts ...grpc.CallOption) (*LifestyleResponse, error)
	SendPatientDementia(ctx context.Context, in *DementiaRequest, opts ...grpc.CallOption) (*DementiaResponse, error)
	GetNews(ctx context.Context, in *NewsRequest, opts ...grpc.CallOption) (*NewsResponse, error)
}

type firestoreClient struct {
	cc grpc.ClientConnInterface
}

func NewFirestoreClient(cc grpc.ClientConnInterface) FirestoreClient {
	return &firestoreClient{cc}
}

func (c *firestoreClient) Register(ctx context.Context, in *UserRegister, opts ...grpc.CallOption) (*RegisterResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResult)
	err := c.cc.Invoke(ctx, Firestore_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firestoreClient) Login(ctx context.Context, in *UserLogin, opts ...grpc.CallOption) (*LoginResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResult)
	err := c.cc.Invoke(ctx, Firestore_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firestoreClient) PatientInfo(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*PatientData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatientData)
	err := c.cc.Invoke(ctx, Firestore_PatientInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firestoreClient) GetRisk(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*RiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskResponse)
	err := c.cc.Invoke(ctx, Firestore_GetRisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firestoreClient) DoctorInfo(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*DoctorData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoctorData)
	err := c.cc.Invoke(ctx, Firestore_DoctorInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firestoreClient) GetPatients(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*PatientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatientsResponse)
	err := c.cc.Invoke(ctx, Firestore_GetPatients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firestoreClient) GetTestHistory(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*TestHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestHistoryResponse)
	err := c.cc.Invoke(ctx, Firestore_GetTestHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firestoreClient) SendLifestyle(ctx context.Context, in *LifestyleRequest, opts ...grpc.CallOption) (*LifestyleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LifestyleResponse)
	err := c.cc.Invoke(ctx, Firestore_SendLifestyle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firestoreClient) SendPatientDementia(ctx context.Context, in *DementiaRequest, opts ...grpc.CallOption) (*DementiaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DementiaResponse)
	err := c.cc.Invoke(ctx, Firestore_SendPatientDementia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firestoreClient) GetNews(ctx context.Context, in *NewsRequest, opts ...grpc.CallOption) (*NewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewsResponse)
	err := c.cc.Invoke(ctx, Firestore_GetNews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FirestoreServer is the server API for Firestore service.
// All implementations must embed UnimplementedFirestoreServer
// for forward compatibility.
type FirestoreServer interface {
	Register(context.Context, *UserRegister) (*RegisterResult, error)
	Login(context.Context, *UserLogin) (*LoginResult, error)
	PatientInfo(context.Context, *UserID) (*PatientData, error)
	GetRisk(context.Context, *UserID) (*RiskResponse, error)
	DoctorInfo(context.Context, *UserID) (*DoctorData, error)
	GetPatients(context.Context, *UserID) (*PatientsResponse, error)
	GetTestHistory(context.Context, *UserID) (*TestHistoryResponse, error)
	SendLifestyle(context.Context, *LifestyleRequest) (*LifestyleResponse, error)
	SendPatientDementia(context.Context, *DementiaRequest) (*DementiaResponse, error)
	GetNews(context.Context, *NewsRequest) (*NewsResponse, error)
	mustEmbedUnimplementedFirestoreServer()
}

// UnimplementedFirestoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFirestoreServer struct{}

func (UnimplementedFirestoreServer) Register(context.Context, *UserRegister) (*RegisterResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedFirestoreServer) Login(context.Context, *UserLogin) (*LoginResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedFirestoreServer) PatientInfo(context.Context, *UserID) (*PatientData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatientInfo not implemented")
}
func (UnimplementedFirestoreServer) GetRisk(context.Context, *UserID) (*RiskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRisk not implemented")
}
func (UnimplementedFirestoreServer) DoctorInfo(context.Context, *UserID) (*DoctorData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoctorInfo not implemented")
}
func (UnimplementedFirestoreServer) GetPatients(context.Context, *UserID) (*PatientsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPatients not implemented")
}
func (UnimplementedFirestoreServer) GetTestHistory(context.Context, *UserID) (*TestHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTestHistory not implemented")
}
func (UnimplementedFirestoreServer) SendLifestyle(context.Context, *LifestyleRequest) (*LifestyleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendLifestyle not implemented")
}
func (UnimplementedFirestoreServer) SendPatientDementia(context.Context, *DementiaRequest) (*DementiaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPatientDementia not implemented")
}
func (UnimplementedFirestoreServer) GetNews(context.Context, *NewsRequest) (*NewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNews not implemented")
}
func (UnimplementedFirestoreServer) mustEmbedUnimplementedFirestoreServer() {}
func (UnimplementedFirestoreServer) testEmbeddedByValue()                   {}

// UnsafeFirestoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FirestoreServer will
// result in compilation errors.
type UnsafeFirestoreServer interface {
	mustEmbedUnimplementedFirestoreServer()
}

func RegisterFirestoreServer(s grpc.ServiceRegistrar, srv FirestoreServer) {
	// If the following call pancis, it indicates UnimplementedFirestoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Firestore_ServiceDesc, srv)
}

func _Firestore_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegister)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirestoreServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Firestore_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirestoreServer).Register(ctx, req.(*UserRegister))
	}
	return interceptor(ctx, in, info, handler)
}

func _Firestore_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLogin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirestoreServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Firestore_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirestoreServer).Login(ctx, req.(*UserLogin))
	}
	return interceptor(ctx, in, info, handler)
}

func _Firestore_PatientInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirestoreServer).PatientInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Firestore_PatientInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirestoreServer).PatientInfo(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Firestore_GetRisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirestoreServer).GetRisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Firestore_GetRisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirestoreServer).GetRisk(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Firestore_DoctorInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirestoreServer).DoctorInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Firestore_DoctorInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirestoreServer).DoctorInfo(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Firestore_GetPatients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirestoreServer).GetPatients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Firestore_GetPatients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirestoreServer).GetPatients(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Firestore_GetTestHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirestoreServer).GetTestHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Firestore_GetTestHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirestoreServer).GetTestHistory(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Firestore_SendLifestyle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LifestyleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirestoreServer).SendLifestyle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Firestore_SendLifestyle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirestoreServer).SendLifestyle(ctx, req.(*LifestyleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Firestore_SendPatientDementia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DementiaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirestoreServer).SendPatientDementia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Firestore_SendPatientDementia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirestoreServer).SendPatientDementia(ctx, req.(*DementiaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Firestore_GetNews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirestoreServer).GetNews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Firestore_GetNews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirestoreServer).GetNews(ctx, req.(*NewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Firestore_ServiceDesc is the grpc.ServiceDesc for Firestore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Firestore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "firestore.firestore",
	HandlerType: (*FirestoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Firestore_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Firestore_Login_Handler,
		},
		{
			MethodName: "PatientInfo",
			Handler:    _Firestore_PatientInfo_Handler,
		},
		{
			MethodName: "GetRisk",
			Handler:    _Firestore_GetRisk_Handler,
		},
		{
			MethodName: "DoctorInfo",
			Handler:    _Firestore_DoctorInfo_Handler,
		},
		{
			MethodName: "GetPatients",
			Handler:    _Firestore_GetPatients_Handler,
		},
		{
			MethodName: "GetTestHistory",
			Handler:    _Firestore_GetTestHistory_Handler,
		},
		{
			MethodName: "SendLifestyle",
			Handler:    _Firestore_SendLifestyle_Handler,
		},
		{
			MethodName: "SendPatientDementia",
			Handler:    _Firestore_SendPatientDementia_Handler,
		},
		{
			MethodName: "GetNews",
			Handler:    _Firestore_GetNews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "firestore.proto",
}
