// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: firestore.proto

package proto_example

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Firestore_Login_FullMethodName         = "/firestore.firestore/Login"
	Firestore_GetDetails_FullMethodName    = "/firestore.firestore/getDetails"
	Firestore_GetRisk_FullMethodName       = "/firestore.firestore/getRisk"
	Firestore_SendLifestyle_FullMethodName = "/firestore.firestore/SendLifestyle"
)

// FirestoreClient is the client API for Firestore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FirestoreClient interface {
	Login(ctx context.Context, in *UserLogin, opts ...grpc.CallOption) (*SessionToken, error)
	GetDetails(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserDetails, error)
	GetRisk(ctx context.Context, in *SessionToken, opts ...grpc.CallOption) (*RiskScore, error)
	SendLifestyle(ctx context.Context, in *LifestyleRequest, opts ...grpc.CallOption) (*LifestyleResponse, error)
}

type firestoreClient struct {
	cc grpc.ClientConnInterface
}

func NewFirestoreClient(cc grpc.ClientConnInterface) FirestoreClient {
	return &firestoreClient{cc}
}

func (c *firestoreClient) Login(ctx context.Context, in *UserLogin, opts ...grpc.CallOption) (*SessionToken, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionToken)
	err := c.cc.Invoke(ctx, Firestore_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firestoreClient) GetDetails(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserDetails)
	err := c.cc.Invoke(ctx, Firestore_GetDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firestoreClient) GetRisk(ctx context.Context, in *SessionToken, opts ...grpc.CallOption) (*RiskScore, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskScore)
	err := c.cc.Invoke(ctx, Firestore_GetRisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firestoreClient) SendLifestyle(ctx context.Context, in *LifestyleRequest, opts ...grpc.CallOption) (*LifestyleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LifestyleResponse)
	err := c.cc.Invoke(ctx, Firestore_SendLifestyle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FirestoreServer is the server API for Firestore service.
// All implementations must embed UnimplementedFirestoreServer
// for forward compatibility.
type FirestoreServer interface {
	Login(context.Context, *UserLogin) (*SessionToken, error)
	GetDetails(context.Context, *UserRequest) (*UserDetails, error)
	GetRisk(context.Context, *SessionToken) (*RiskScore, error)
	SendLifestyle(context.Context, *LifestyleRequest) (*LifestyleResponse, error)
	mustEmbedUnimplementedFirestoreServer()
}

// UnimplementedFirestoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFirestoreServer struct{}

func (UnimplementedFirestoreServer) Login(context.Context, *UserLogin) (*SessionToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedFirestoreServer) GetDetails(context.Context, *UserRequest) (*UserDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDetails not implemented")
}
func (UnimplementedFirestoreServer) GetRisk(context.Context, *SessionToken) (*RiskScore, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRisk not implemented")
}
func (UnimplementedFirestoreServer) SendLifestyle(context.Context, *LifestyleRequest) (*LifestyleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendLifestyle not implemented")
}
func (UnimplementedFirestoreServer) mustEmbedUnimplementedFirestoreServer() {}
func (UnimplementedFirestoreServer) testEmbeddedByValue()                   {}

// UnsafeFirestoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FirestoreServer will
// result in compilation errors.
type UnsafeFirestoreServer interface {
	mustEmbedUnimplementedFirestoreServer()
}

func RegisterFirestoreServer(s grpc.ServiceRegistrar, srv FirestoreServer) {
	// If the following call pancis, it indicates UnimplementedFirestoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Firestore_ServiceDesc, srv)
}

func _Firestore_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLogin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirestoreServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Firestore_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirestoreServer).Login(ctx, req.(*UserLogin))
	}
	return interceptor(ctx, in, info, handler)
}

func _Firestore_GetDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirestoreServer).GetDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Firestore_GetDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirestoreServer).GetDetails(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Firestore_GetRisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirestoreServer).GetRisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Firestore_GetRisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirestoreServer).GetRisk(ctx, req.(*SessionToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _Firestore_SendLifestyle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LifestyleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirestoreServer).SendLifestyle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Firestore_SendLifestyle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirestoreServer).SendLifestyle(ctx, req.(*LifestyleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Firestore_ServiceDesc is the grpc.ServiceDesc for Firestore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Firestore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "firestore.firestore",
	HandlerType: (*FirestoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Firestore_Login_Handler,
		},
		{
			MethodName: "getDetails",
			Handler:    _Firestore_GetDetails_Handler,
		},
		{
			MethodName: "getRisk",
			Handler:    _Firestore_GetRisk_Handler,
		},
		{
			MethodName: "SendLifestyle",
			Handler:    _Firestore_SendLifestyle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "firestore.proto",
}
