// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: user_service.proto

package user_service

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *SignUpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`                        //may be null
	IdToken       string                 `protobuf:"bytes,2,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"` //may be null
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthReply) Reset() {
	*x = AuthReply{}
	mi := &file_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReply) ProtoMessage() {}

func (x *AuthReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReply.ProtoReflect.Descriptor instead.
func (*AuthReply) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *AuthReply) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *AuthReply) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

func (x *AuthReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LinkUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientToken  string                 `protobuf:"bytes,1,opt,name=patient_token,json=patientToken,proto3" json:"patient_token,omitempty"`
	DoctorUid     string                 `protobuf:"bytes,2,opt,name=doctor_uid,json=doctorUid,proto3" json:"doctor_uid,omitempty"`
	RelationType  string                 `protobuf:"bytes,3,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"` // e.g. "doctor" (for filtering options, not nessesary)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkUserRequest) Reset() {
	*x = LinkUserRequest{}
	mi := &file_user_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkUserRequest) ProtoMessage() {}

func (x *LinkUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkUserRequest.ProtoReflect.Descriptor instead.
func (*LinkUserRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{3}
}

func (x *LinkUserRequest) GetPatientToken() string {
	if x != nil {
		return x.PatientToken
	}
	return ""
}

func (x *LinkUserRequest) GetDoctorUid() string {
	if x != nil {
		return x.DoctorUid
	}
	return ""
}

func (x *LinkUserRequest) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

type LinkUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkUserReply) Reset() {
	*x = LinkUserReply{}
	mi := &file_user_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkUserReply) ProtoMessage() {}

func (x *LinkUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkUserReply.ProtoReflect.Descriptor instead.
func (*LinkUserReply) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{4}
}

func (x *LinkUserReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetLinkedUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdToken       string                 `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	RelationType  string                 `protobuf:"bytes,2,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"` //optional for filtering
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkedUsersRequest) Reset() {
	*x = GetLinkedUsersRequest{}
	mi := &file_user_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkedUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkedUsersRequest) ProtoMessage() {}

func (x *GetLinkedUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkedUsersRequest.ProtoReflect.Descriptor instead.
func (*GetLinkedUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetLinkedUsersRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

func (x *GetLinkedUsersRequest) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

type RelatedUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	RelationType  string                 `protobuf:"bytes,2,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelatedUser) Reset() {
	*x = RelatedUser{}
	mi := &file_user_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelatedUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelatedUser) ProtoMessage() {}

func (x *RelatedUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelatedUser.ProtoReflect.Descriptor instead.
func (*RelatedUser) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{6}
}

func (x *RelatedUser) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *RelatedUser) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

type GetLinkedUsersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelatedUsers  []*RelatedUser         `protobuf:"bytes,1,rep,name=related_users,json=relatedUsers,proto3" json:"related_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkedUsersReply) Reset() {
	*x = GetLinkedUsersReply{}
	mi := &file_user_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkedUsersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkedUsersReply) ProtoMessage() {}

func (x *GetLinkedUsersReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkedUsersReply.ProtoReflect.Descriptor instead.
func (*GetLinkedUsersReply) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetLinkedUsersReply) GetRelatedUsers() []*RelatedUser {
	if x != nil {
		return x.RelatedUsers
	}
	return nil
}

type AddUserDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdToken       string                 `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // arbitrary key-value fields
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserDetailsRequest) Reset() {
	*x = AddUserDetailsRequest{}
	mi := &file_user_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserDetailsRequest) ProtoMessage() {}

func (x *AddUserDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserDetailsRequest.ProtoReflect.Descriptor instead.
func (*AddUserDetailsRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{8}
}

func (x *AddUserDetailsRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

func (x *AddUserDetailsRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *AddUserDetailsRequest) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type AddUserDetailsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserDetailsReply) Reset() {
	*x = AddUserDetailsReply{}
	mi := &file_user_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserDetailsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserDetailsReply) ProtoMessage() {}

func (x *AddUserDetailsReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserDetailsReply.ProtoReflect.Descriptor instead.
func (*AddUserDetailsReply) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{9}
}

func (x *AddUserDetailsReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdToken       string                 `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`       // requester token
	TargetUid     string                 `protobuf:"bytes,2,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"` // optional - uid of related user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDetailsRequest) Reset() {
	*x = GetUserDetailsRequest{}
	mi := &file_user_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDetailsRequest) ProtoMessage() {}

func (x *GetUserDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetUserDetailsRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserDetailsRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

func (x *GetUserDetailsRequest) GetTargetUid() string {
	if x != nil {
		return x.TargetUid
	}
	return ""
}

type GetUserDetailsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       map[string]string      `protobuf:"bytes,1,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDetailsReply) Reset() {
	*x = GetUserDetailsReply{}
	mi := &file_user_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDetailsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDetailsReply) ProtoMessage() {}

func (x *GetUserDetailsReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDetailsReply.ProtoReflect.Descriptor instead.
func (*GetUserDetailsReply) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserDetailsReply) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type VerifyTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdToken       string                 `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_user_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{12}
}

func (x *VerifyTokenRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

type VerifyTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           bool                   `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_user_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{13}
}

func (x *VerifyTokenResponse) GetRes() bool {
	if x != nil {
		return x.Res
	}
	return false
}

func (x *VerifyTokenResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type AddTestResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdToken       string                 `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`         // identifies the user
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                              // unstructured data (JSON, text, etc.)
	RiskScore     float32                `protobuf:"fixed32,3,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"` // calculated risk score
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTestResultRequest) Reset() {
	*x = AddTestResultRequest{}
	mi := &file_user_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTestResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTestResultRequest) ProtoMessage() {}

func (x *AddTestResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTestResultRequest.ProtoReflect.Descriptor instead.
func (*AddTestResultRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{14}
}

func (x *AddTestResultRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

func (x *AddTestResultRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *AddTestResultRequest) GetRiskScore() float32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

type AddTestResultReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTestResultReply) Reset() {
	*x = AddTestResultReply{}
	mi := &file_user_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTestResultReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTestResultReply) ProtoMessage() {}

func (x *AddTestResultReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTestResultReply.ProtoReflect.Descriptor instead.
func (*AddTestResultReply) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{15}
}

func (x *AddTestResultReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserTestResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdToken       string                 `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`       // requester
	TargetUid     string                 `protobuf:"bytes,2,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"` // patient uid (optional, defaults to self)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTestResultsRequest) Reset() {
	*x = GetUserTestResultsRequest{}
	mi := &file_user_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTestResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTestResultsRequest) ProtoMessage() {}

func (x *GetUserTestResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTestResultsRequest.ProtoReflect.Descriptor instead.
func (*GetUserTestResultsRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserTestResultsRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

func (x *GetUserTestResultsRequest) GetTargetUid() string {
	if x != nil {
		return x.TargetUid
	}
	return ""
}

type TestSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	RiskScore     string                 `protobuf:"bytes,3,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestSummary) Reset() {
	*x = TestSummary{}
	mi := &file_user_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestSummary) ProtoMessage() {}

func (x *TestSummary) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestSummary.ProtoReflect.Descriptor instead.
func (*TestSummary) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{17}
}

func (x *TestSummary) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *TestSummary) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TestSummary) GetRiskScore() string {
	if x != nil {
		return x.RiskScore
	}
	return ""
}

func (x *TestSummary) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GetUserTestResultsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tests         []*TestSummary         `protobuf:"bytes,1,rep,name=tests,proto3" json:"tests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTestResultsReply) Reset() {
	*x = GetUserTestResultsReply{}
	mi := &file_user_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTestResultsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTestResultsReply) ProtoMessage() {}

func (x *GetUserTestResultsReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTestResultsReply.ProtoReflect.Descriptor instead.
func (*GetUserTestResultsReply) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserTestResultsReply) GetTests() []*TestSummary {
	if x != nil {
		return x.Tests
	}
	return nil
}

type GetTestResultDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdToken       string                 `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	TestId        string                 `protobuf:"bytes,2,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTestResultDetailsRequest) Reset() {
	*x = GetTestResultDetailsRequest{}
	mi := &file_user_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTestResultDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestResultDetailsRequest) ProtoMessage() {}

func (x *GetTestResultDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestResultDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetTestResultDetailsRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetTestResultDetailsRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

func (x *GetTestResultDetailsRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

type GetTestResultDetailsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Test          map[string]string      `protobuf:"bytes,1,rep,name=test,proto3" json:"test,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTestResultDetailsReply) Reset() {
	*x = GetTestResultDetailsReply{}
	mi := &file_user_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTestResultDetailsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestResultDetailsReply) ProtoMessage() {}

func (x *GetTestResultDetailsReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestResultDetailsReply.ProtoReflect.Descriptor instead.
func (*GetTestResultDetailsReply) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetTestResultDetailsReply) GetTest() map[string]string {
	if x != nil {
		return x.Test
	}
	return nil
}

var File_user_service_proto protoreflect.FileDescriptor

const file_user_service_proto_rawDesc = "" +
	"\n" +
	"\x12user_service.proto\x12\fuser_service\x1a\x1cgoogle/api/annotations.proto\"A\n" +
	"\rSignUpRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"R\n" +
	"\tAuthReply\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x19\n" +
	"\bid_token\x18\x02 \x01(\tR\aidToken\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"z\n" +
	"\x0fLinkUserRequest\x12#\n" +
	"\rpatient_token\x18\x01 \x01(\tR\fpatientToken\x12\x1d\n" +
	"\n" +
	"doctor_uid\x18\x02 \x01(\tR\tdoctorUid\x12#\n" +
	"\rrelation_type\x18\x03 \x01(\tR\frelationType\")\n" +
	"\rLinkUserReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"W\n" +
	"\x15GetLinkedUsersRequest\x12\x19\n" +
	"\bid_token\x18\x01 \x01(\tR\aidToken\x12#\n" +
	"\rrelation_type\x18\x02 \x01(\tR\frelationType\"D\n" +
	"\vRelatedUser\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12#\n" +
	"\rrelation_type\x18\x02 \x01(\tR\frelationType\"U\n" +
	"\x13GetLinkedUsersReply\x12>\n" +
	"\rrelated_users\x18\x01 \x03(\v2\x19.user_service.RelatedUserR\frelatedUsers\"\xcc\x01\n" +
	"\x15AddUserDetailsRequest\x12\x19\n" +
	"\bid_token\x18\x01 \x01(\tR\aidToken\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12J\n" +
	"\adetails\x18\x03 \x03(\v20.user_service.AddUserDetailsRequest.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x13AddUserDetailsReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"Q\n" +
	"\x15GetUserDetailsRequest\x12\x19\n" +
	"\bid_token\x18\x01 \x01(\tR\aidToken\x12\x1d\n" +
	"\n" +
	"target_uid\x18\x02 \x01(\tR\ttargetUid\"\x9b\x01\n" +
	"\x13GetUserDetailsReply\x12H\n" +
	"\adetails\x18\x01 \x03(\v2..user_service.GetUserDetailsReply.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x12VerifyTokenRequest\x12\x19\n" +
	"\bid_token\x18\x01 \x01(\tR\aidToken\"9\n" +
	"\x13VerifyTokenResponse\x12\x10\n" +
	"\x03res\x18\x01 \x01(\bR\x03res\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\"d\n" +
	"\x14AddTestResultRequest\x12\x19\n" +
	"\bid_token\x18\x01 \x01(\tR\aidToken\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x03 \x01(\x02R\triskScore\".\n" +
	"\x12AddTestResultReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"U\n" +
	"\x19GetUserTestResultsRequest\x12\x19\n" +
	"\bid_token\x18\x01 \x01(\tR\aidToken\x12\x1d\n" +
	"\n" +
	"target_uid\x18\x02 \x01(\tR\ttargetUid\"m\n" +
	"\vTestSummary\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x03 \x01(\tR\triskScore\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\"J\n" +
	"\x17GetUserTestResultsReply\x12/\n" +
	"\x05tests\x18\x01 \x03(\v2\x19.user_service.TestSummaryR\x05tests\"Q\n" +
	"\x1bGetTestResultDetailsRequest\x12\x19\n" +
	"\bid_token\x18\x01 \x01(\tR\aidToken\x12\x17\n" +
	"\atest_id\x18\x02 \x01(\tR\x06testId\"\x9b\x01\n" +
	"\x19GetTestResultDetailsReply\x12E\n" +
	"\x04test\x18\x01 \x03(\v21.user_service.GetTestResultDetailsReply.TestEntryR\x04test\x1a7\n" +
	"\tTestEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xcd\n" +
	"\n" +
	"\vUserService\x12\x90\x01\n" +
	"\x0eAddUserDetails\x12#.user_service.AddUserDetailsRequest\x1a!.user_service.AddUserDetailsReply\"6\x82\xd3\xe4\x93\x020:\x01*\x1a+/v1/user_service.UserService/AddUserDetails\x12\x8c\x01\n" +
	"\rAddTestResult\x12\".user_service.AddTestResultRequest\x1a .user_service.AddTestResultReply\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/v1/user_service.UserService/AddTestResult\x12\x8d\x01\n" +
	"\x0eGetUserDetails\x12#.user_service.GetUserDetailsRequest\x1a!.user_service.GetUserDetailsReply\"3\x82\xd3\xe4\x93\x02-\x12+/v1/user_service.UserService/GetUserDetails\x12k\n" +
	"\x05Login\x12\x1a.user_service.LoginRequest\x1a\x17.user_service.AuthReply\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/user_service.UserService/Login\x12n\n" +
	"\x06SignUp\x12\x1b.user_service.SignUpRequest\x1a\x17.user_service.AuthReply\".\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/user_service.UserService/SignUp\x12x\n" +
	"\bLinkUser\x12\x1d.user_service.LinkUserRequest\x1a\x1b.user_service.LinkUserReply\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/v1/user_service.UserService/LinkUser\x12\x90\x01\n" +
	"\x0eGetLinkedUsers\x12#.user_service.GetLinkedUsersRequest\x1a!.user_service.GetLinkedUsersReply\"6\x82\xd3\xe4\x93\x020:\x01*\"+/v1/user_service.UserService/GetLinkedUsers\x12Z\n" +
	"\x11VerifyTokenRemote\x12 .user_service.VerifyTokenRequest\x1a!.user_service.VerifyTokenResponse\"\x00\x12\x9d\x01\n" +
	"\x12GetUserTestResults\x12'.user_service.GetUserTestResultsRequest\x1a%.user_service.GetUserTestResultsReply\"7\x82\xd3\xe4\x93\x021\x12//v1/user_service.UserService/GetUserTestResults\x12\xa5\x01\n" +
	"\x14GetTestResultDetails\x12).user_service.GetTestResultDetailsRequest\x1a'.user_service.GetTestResultDetailsReply\"9\x82\xd3\xe4\x93\x023\x121/v1/user_service.UserService/GetTestResultDetailsB\x16Z\x14example/user_serviceb\x06proto3"

var (
	file_user_service_proto_rawDescOnce sync.Once
	file_user_service_proto_rawDescData []byte
)

func file_user_service_proto_rawDescGZIP() []byte {
	file_user_service_proto_rawDescOnce.Do(func() {
		file_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_proto_rawDesc), len(file_user_service_proto_rawDesc)))
	})
	return file_user_service_proto_rawDescData
}

var file_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_user_service_proto_goTypes = []any{
	(*SignUpRequest)(nil),               // 0: user_service.SignUpRequest
	(*LoginRequest)(nil),                // 1: user_service.LoginRequest
	(*AuthReply)(nil),                   // 2: user_service.AuthReply
	(*LinkUserRequest)(nil),             // 3: user_service.LinkUserRequest
	(*LinkUserReply)(nil),               // 4: user_service.LinkUserReply
	(*GetLinkedUsersRequest)(nil),       // 5: user_service.GetLinkedUsersRequest
	(*RelatedUser)(nil),                 // 6: user_service.RelatedUser
	(*GetLinkedUsersReply)(nil),         // 7: user_service.GetLinkedUsersReply
	(*AddUserDetailsRequest)(nil),       // 8: user_service.AddUserDetailsRequest
	(*AddUserDetailsReply)(nil),         // 9: user_service.AddUserDetailsReply
	(*GetUserDetailsRequest)(nil),       // 10: user_service.GetUserDetailsRequest
	(*GetUserDetailsReply)(nil),         // 11: user_service.GetUserDetailsReply
	(*VerifyTokenRequest)(nil),          // 12: user_service.VerifyTokenRequest
	(*VerifyTokenResponse)(nil),         // 13: user_service.VerifyTokenResponse
	(*AddTestResultRequest)(nil),        // 14: user_service.AddTestResultRequest
	(*AddTestResultReply)(nil),          // 15: user_service.AddTestResultReply
	(*GetUserTestResultsRequest)(nil),   // 16: user_service.GetUserTestResultsRequest
	(*TestSummary)(nil),                 // 17: user_service.TestSummary
	(*GetUserTestResultsReply)(nil),     // 18: user_service.GetUserTestResultsReply
	(*GetTestResultDetailsRequest)(nil), // 19: user_service.GetTestResultDetailsRequest
	(*GetTestResultDetailsReply)(nil),   // 20: user_service.GetTestResultDetailsReply
	nil,                                 // 21: user_service.AddUserDetailsRequest.DetailsEntry
	nil,                                 // 22: user_service.GetUserDetailsReply.DetailsEntry
	nil,                                 // 23: user_service.GetTestResultDetailsReply.TestEntry
}
var file_user_service_proto_depIdxs = []int32{
	6,  // 0: user_service.GetLinkedUsersReply.related_users:type_name -> user_service.RelatedUser
	21, // 1: user_service.AddUserDetailsRequest.details:type_name -> user_service.AddUserDetailsRequest.DetailsEntry
	22, // 2: user_service.GetUserDetailsReply.details:type_name -> user_service.GetUserDetailsReply.DetailsEntry
	17, // 3: user_service.GetUserTestResultsReply.tests:type_name -> user_service.TestSummary
	23, // 4: user_service.GetTestResultDetailsReply.test:type_name -> user_service.GetTestResultDetailsReply.TestEntry
	8,  // 5: user_service.UserService.AddUserDetails:input_type -> user_service.AddUserDetailsRequest
	14, // 6: user_service.UserService.AddTestResult:input_type -> user_service.AddTestResultRequest
	10, // 7: user_service.UserService.GetUserDetails:input_type -> user_service.GetUserDetailsRequest
	1,  // 8: user_service.UserService.Login:input_type -> user_service.LoginRequest
	0,  // 9: user_service.UserService.SignUp:input_type -> user_service.SignUpRequest
	3,  // 10: user_service.UserService.LinkUser:input_type -> user_service.LinkUserRequest
	5,  // 11: user_service.UserService.GetLinkedUsers:input_type -> user_service.GetLinkedUsersRequest
	12, // 12: user_service.UserService.VerifyTokenRemote:input_type -> user_service.VerifyTokenRequest
	16, // 13: user_service.UserService.GetUserTestResults:input_type -> user_service.GetUserTestResultsRequest
	19, // 14: user_service.UserService.GetTestResultDetails:input_type -> user_service.GetTestResultDetailsRequest
	9,  // 15: user_service.UserService.AddUserDetails:output_type -> user_service.AddUserDetailsReply
	15, // 16: user_service.UserService.AddTestResult:output_type -> user_service.AddTestResultReply
	11, // 17: user_service.UserService.GetUserDetails:output_type -> user_service.GetUserDetailsReply
	2,  // 18: user_service.UserService.Login:output_type -> user_service.AuthReply
	2,  // 19: user_service.UserService.SignUp:output_type -> user_service.AuthReply
	4,  // 20: user_service.UserService.LinkUser:output_type -> user_service.LinkUserReply
	7,  // 21: user_service.UserService.GetLinkedUsers:output_type -> user_service.GetLinkedUsersReply
	13, // 22: user_service.UserService.VerifyTokenRemote:output_type -> user_service.VerifyTokenResponse
	18, // 23: user_service.UserService.GetUserTestResults:output_type -> user_service.GetUserTestResultsReply
	20, // 24: user_service.UserService.GetTestResultDetails:output_type -> user_service.GetTestResultDetailsReply
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_user_service_proto_init() }
func file_user_service_proto_init() {
	if File_user_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_proto_rawDesc), len(file_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_proto_goTypes,
		DependencyIndexes: file_user_service_proto_depIdxs,
		MessageInfos:      file_user_service_proto_msgTypes,
	}.Build()
	File_user_service_proto = out.File
	file_user_service_proto_goTypes = nil
	file_user_service_proto_depIdxs = nil
}
