// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: firebase.proto

package proto_example

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserLogin struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserName          string                 `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	PlaintextPassword string                 `protobuf:"bytes,2,opt,name=PlaintextPassword,proto3" json:"PlaintextPassword,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserLogin) Reset() {
	*x = UserLogin{}
	mi := &file_firebase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogin) ProtoMessage() {}

func (x *UserLogin) ProtoReflect() protoreflect.Message {
	mi := &file_firebase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogin.ProtoReflect.Descriptor instead.
func (*UserLogin) Descriptor() ([]byte, []int) {
	return file_firebase_proto_rawDescGZIP(), []int{0}
}

func (x *UserLogin) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserLogin) GetPlaintextPassword() string {
	if x != nil {
		return x.PlaintextPassword
	}
	return ""
}

type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_firebase_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_firebase_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_firebase_proto_rawDescGZIP(), []int{1}
}

func (x *UserID) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  int64                  `protobuf:"varint,1,opt,name=SessionToken,proto3" json:"SessionToken,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_firebase_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_firebase_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_firebase_proto_rawDescGZIP(), []int{2}
}

func (x *UserRequest) GetSessionToken() int64 {
	if x != nil {
		return x.SessionToken
	}
	return 0
}

func (x *UserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SessionToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temp          int64                  `protobuf:"varint,1,opt,name=Temp,proto3" json:"Temp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionToken) Reset() {
	*x = SessionToken{}
	mi := &file_firebase_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionToken) ProtoMessage() {}

func (x *SessionToken) ProtoReflect() protoreflect.Message {
	mi := &file_firebase_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionToken.ProtoReflect.Descriptor instead.
func (*SessionToken) Descriptor() ([]byte, []int) {
	return file_firebase_proto_rawDescGZIP(), []int{3}
}

func (x *SessionToken) GetTemp() int64 {
	if x != nil {
		return x.Temp
	}
	return 0
}

type UserDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       string                 `protobuf:"bytes,1,opt,name=Details,proto3" json:"Details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetails) Reset() {
	*x = UserDetails{}
	mi := &file_firebase_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetails) ProtoMessage() {}

func (x *UserDetails) ProtoReflect() protoreflect.Message {
	mi := &file_firebase_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetails.ProtoReflect.Descriptor instead.
func (*UserDetails) Descriptor() ([]byte, []int) {
	return file_firebase_proto_rawDescGZIP(), []int{4}
}

func (x *UserDetails) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type RiskScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int32                  `protobuf:"varint,1,opt,name=Score,proto3" json:"Score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskScore) Reset() {
	*x = RiskScore{}
	mi := &file_firebase_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskScore) ProtoMessage() {}

func (x *RiskScore) ProtoReflect() protoreflect.Message {
	mi := &file_firebase_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskScore.ProtoReflect.Descriptor instead.
func (*RiskScore) Descriptor() ([]byte, []int) {
	return file_firebase_proto_rawDescGZIP(), []int{5}
}

func (x *RiskScore) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type LifestyleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifestyleRequest) Reset() {
	*x = LifestyleRequest{}
	mi := &file_firebase_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifestyleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifestyleRequest) ProtoMessage() {}

func (x *LifestyleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_firebase_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifestyleRequest.ProtoReflect.Descriptor instead.
func (*LifestyleRequest) Descriptor() ([]byte, []int) {
	return file_firebase_proto_rawDescGZIP(), []int{6}
}

func (x *LifestyleRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LifestyleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifestyleResponse) Reset() {
	*x = LifestyleResponse{}
	mi := &file_firebase_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifestyleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifestyleResponse) ProtoMessage() {}

func (x *LifestyleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_firebase_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifestyleResponse.ProtoReflect.Descriptor instead.
func (*LifestyleResponse) Descriptor() ([]byte, []int) {
	return file_firebase_proto_rawDescGZIP(), []int{7}
}

func (x *LifestyleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_firebase_proto protoreflect.FileDescriptor

const file_firebase_proto_rawDesc = "" +
	"\n" +
	"\x0efirebase.proto\x12\x11firebaseprototype\x1a\x1cgoogle/api/annotations.proto\"U\n" +
	"\tUserLogin\x12\x1a\n" +
	"\bUserName\x18\x01 \x01(\tR\bUserName\x12,\n" +
	"\x11PlaintextPassword\x18\x02 \x01(\tR\x11PlaintextPassword\"$\n" +
	"\x06UserID\x12\x1a\n" +
	"\bUserName\x18\x01 \x01(\tR\bUserName\"I\n" +
	"\vUserRequest\x12\"\n" +
	"\fSessionToken\x18\x01 \x01(\x03R\fSessionToken\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\tR\x06UserId\"\"\n" +
	"\fSessionToken\x12\x12\n" +
	"\x04Temp\x18\x01 \x01(\x03R\x04Temp\"'\n" +
	"\vUserDetails\x12\x18\n" +
	"\aDetails\x18\x01 \x01(\tR\aDetails\"!\n" +
	"\tRiskScore\x12\x14\n" +
	"\x05Score\x18\x01 \x01(\x05R\x05Score\",\n" +
	"\x10LifestyleRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"-\n" +
	"\x11LifestyleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xac\x03\n" +
	"\x04serv\x12\\\n" +
	"\x05Login\x12\x1c.firebaseprototype.UserLogin\x1a\x1f.firebaseprototype.SessionToken\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/login\x12h\n" +
	"\n" +
	"getDetails\x12\x1e.firebaseprototype.UserRequest\x1a\x1e.firebaseprototype.UserDetails\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/get_details\x12a\n" +
	"\agetRisk\x12\x1f.firebaseprototype.SessionToken\x1a\x1c.firebaseprototype.RiskScore\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/get_risk\x12y\n" +
	"\rSendLifestyle\x12#.firebaseprototype.LifestyleRequest\x1a$.firebaseprototype.LifestyleResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/send_lifestyleB-\n" +
	"\x14com.example.testgrpcZ\x15example/proto_exampleb\x06proto3"

var (
	file_firebase_proto_rawDescOnce sync.Once
	file_firebase_proto_rawDescData []byte
)

func file_firebase_proto_rawDescGZIP() []byte {
	file_firebase_proto_rawDescOnce.Do(func() {
		file_firebase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_firebase_proto_rawDesc), len(file_firebase_proto_rawDesc)))
	})
	return file_firebase_proto_rawDescData
}

var file_firebase_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_firebase_proto_goTypes = []any{
	(*UserLogin)(nil),         // 0: firebaseprototype.UserLogin
	(*UserID)(nil),            // 1: firebaseprototype.UserID
	(*UserRequest)(nil),       // 2: firebaseprototype.UserRequest
	(*SessionToken)(nil),      // 3: firebaseprototype.SessionToken
	(*UserDetails)(nil),       // 4: firebaseprototype.UserDetails
	(*RiskScore)(nil),         // 5: firebaseprototype.RiskScore
	(*LifestyleRequest)(nil),  // 6: firebaseprototype.LifestyleRequest
	(*LifestyleResponse)(nil), // 7: firebaseprototype.LifestyleResponse
}
var file_firebase_proto_depIdxs = []int32{
	0, // 0: firebaseprototype.serv.Login:input_type -> firebaseprototype.UserLogin
	2, // 1: firebaseprototype.serv.getDetails:input_type -> firebaseprototype.UserRequest
	3, // 2: firebaseprototype.serv.getRisk:input_type -> firebaseprototype.SessionToken
	6, // 3: firebaseprototype.serv.SendLifestyle:input_type -> firebaseprototype.LifestyleRequest
	3, // 4: firebaseprototype.serv.Login:output_type -> firebaseprototype.SessionToken
	4, // 5: firebaseprototype.serv.getDetails:output_type -> firebaseprototype.UserDetails
	5, // 6: firebaseprototype.serv.getRisk:output_type -> firebaseprototype.RiskScore
	7, // 7: firebaseprototype.serv.SendLifestyle:output_type -> firebaseprototype.LifestyleResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_firebase_proto_init() }
func file_firebase_proto_init() {
	if File_firebase_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_firebase_proto_rawDesc), len(file_firebase_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_firebase_proto_goTypes,
		DependencyIndexes: file_firebase_proto_depIdxs,
		MessageInfos:      file_firebase_proto_msgTypes,
	}.Build()
	File_firebase_proto = out.File
	file_firebase_proto_goTypes = nil
	file_firebase_proto_depIdxs = nil
}
