// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: vertex.proto

package aiProompt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProomptMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProomptMsg) Reset() {
	*x = ProomptMsg{}
	mi := &file_vertex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProomptMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProomptMsg) ProtoMessage() {}

func (x *ProomptMsg) ProtoReflect() protoreflect.Message {
	mi := &file_vertex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProomptMsg.ProtoReflect.Descriptor instead.
func (*ProomptMsg) Descriptor() ([]byte, []int) {
	return file_vertex_proto_rawDescGZIP(), []int{0}
}

func (x *ProomptMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProomptReturn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProomptReturn) Reset() {
	*x = ProomptReturn{}
	mi := &file_vertex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProomptReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProomptReturn) ProtoMessage() {}

func (x *ProomptReturn) ProtoReflect() protoreflect.Message {
	mi := &file_vertex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProomptReturn.ProtoReflect.Descriptor instead.
func (*ProomptReturn) Descriptor() ([]byte, []int) {
	return file_vertex_proto_rawDescGZIP(), []int{1}
}

func (x *ProomptReturn) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_vertex_proto protoreflect.FileDescriptor

const file_vertex_proto_rawDesc = "" +
	"\n" +
	"\fvertex.proto\x12\taiProompt\"&\n" +
	"\n" +
	"ProomptMsg\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\")\n" +
	"\rProomptReturn\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2P\n" +
	"\taiProompt\x12C\n" +
	"\x10HealtcareProompt\x12\x15.aiProompt.ProomptMsg\x1a\x18.aiProompt.ProomptReturnB\x13Z\x11example/aiProomptb\x06proto3"

var (
	file_vertex_proto_rawDescOnce sync.Once
	file_vertex_proto_rawDescData []byte
)

func file_vertex_proto_rawDescGZIP() []byte {
	file_vertex_proto_rawDescOnce.Do(func() {
		file_vertex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vertex_proto_rawDesc), len(file_vertex_proto_rawDesc)))
	})
	return file_vertex_proto_rawDescData
}

var file_vertex_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vertex_proto_goTypes = []any{
	(*ProomptMsg)(nil),    // 0: aiProompt.ProomptMsg
	(*ProomptReturn)(nil), // 1: aiProompt.ProomptReturn
}
var file_vertex_proto_depIdxs = []int32{
	0, // 0: aiProompt.aiProompt.HealtcareProompt:input_type -> aiProompt.ProomptMsg
	1, // 1: aiProompt.aiProompt.HealtcareProompt:output_type -> aiProompt.ProomptReturn
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vertex_proto_init() }
func file_vertex_proto_init() {
	if File_vertex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vertex_proto_rawDesc), len(file_vertex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vertex_proto_goTypes,
		DependencyIndexes: file_vertex_proto_depIdxs,
		MessageInfos:      file_vertex_proto_msgTypes,
	}.Build()
	File_vertex_proto = out.File
	file_vertex_proto_goTypes = nil
	file_vertex_proto_depIdxs = nil
}
