# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vertex_pb2 as vertex__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vertex_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class aiProomptStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealtcareProompt = channel.unary_unary(
                '/aiProompt.aiProompt/HealtcareProompt',
                request_serializer=vertex__pb2.ProomptMsg.SerializeToString,
                response_deserializer=vertex__pb2.ProomptReturn.FromString,
                _registered_method=True)


class aiProomptServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HealtcareProompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_aiProomptServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealtcareProompt': grpc.unary_unary_rpc_method_handler(
                    servicer.HealtcareProompt,
                    request_deserializer=vertex__pb2.ProomptMsg.FromString,
                    response_serializer=vertex__pb2.ProomptReturn.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiProompt.aiProompt', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiProompt.aiProompt', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class aiProompt(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HealtcareProompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiProompt.aiProompt/HealtcareProompt',
            vertex__pb2.ProomptMsg.SerializeToString,
            vertex__pb2.ProomptReturn.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
